[package]
name = "my-rust-book"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "hello"
path = "src/main.rs"

[[bin]]
name = "function_for"
path = "src/function_for/main.rs"

[[bin]]
name = "if_return_value"
path = "src/if/main.rs"

[[bin]]
name = "mutable_var"
path = "src/mutable_var/main.rs"

[[bin]]
name = "as"
path = "src/as/main.rs"

[[bin]]
name = "match"
path = "src/match/main.rs"

[[bin]]
name = "expr"
path = "src/expr/main.rs"

[[bin]]
name = "array_slice"
path = "src/array_slice/main.rs"

[[bin]]
name = "string"
path = "src/string/main.rs"

[[bin]]
name = "ownership"
path = "src/ownership/main.rs"

[[bin]]
name = "struct"
path = "src/struct/main.rs"